ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'
urlpatterns = [
    path('add_to_cart/<slug:p>',views.add_to_cart,name='add_to_cart'),
    path('cart_remove/<int:p>',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:p>', views.full_remove, name='full_remove'),
    path('cartview', views.cartview, name='cartview'),
    path('orderform', views.orderform, name='orderform'),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name='search'
urlpatterns = [
    path('',views.searchresults,name='searchresults'),
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name='shop'
urlpatterns = [
    path('',views.allprodcat,name='allprodcat'),
    path('products/<slug:p>', views.allproducts, name='allproducts'),
    path('detail/<slug:p>',views.detail,name='detail'),
    path('register', views.register, name='register'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Products
from django.contrib.auth.models import User

class Cart(models.Model):
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateField(auto_now_add=True)

    def subtotal(self):
        return self.quantity*self.product.price

    def __str__(self):
        return self.product.name

class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    address=models.TextField()
    phone=models.CharField(max_length=100)
    order_status=models.CharField(max_length=30)
    delivery_status=models.CharField(max_length=30,default='Pending')
    noofitems=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username

class Account(models.Model):
    acctnumber=models.CharField(max_length=30)
    acctype=models.CharField(max_length=30)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnumber

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    images=models.ImageField(upload_to='shop/category',null=True,blank=True)
    def __str__(self):
        return self.name

class Products(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    images=models.ImageField(upload_to='shop/products',null=True,blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from shop.models import Products
from cart.models import Cart,Account,Order

def cartview(request):
    total=0
    user=request.user
    try:
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity*i.product.price

    except Cart.DoesNotExist:
        pass
    return render(request,'cartview.html',{'cart':cart,'total': total})


def add_to_cart(request,p):
    p=Products.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,product=p)
        if(cart.quantity<cart.product.stock):
            cart.quantity+=1
            cart.save()
    except Cart.DoesNotExist:
            cart=Cart.objects.create(user=user,product=p,quantity=1)
            cart.save()


    return redirect('cart:cartview')


def cart_remove(request,p):
    p = Products.objects.get(id=p)
    user = request.user
    try:
        cart=Cart.objects.get(user=user, product=p)
        if(cart.quantity>1):
            cart.quantity-=1
            cart.save()
        else:
            cart.delete()
    except Cart.DoesNotExist:
        pass
    return redirect('cart:cartview')

def full_remove(request,p):
    p = Products.objects.get(id=p)
    user=request.user
    try:
        cart = Cart.objects.get(user=user, product=p)

        cart.delete()
    except Cart.DoesNotExist:
        pass
    return redirect('cart:cartview')


def orderform(request):
    total=0
    if(request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']
        user=request.user
        cart=Cart.objects.filter(user=user)
        for i in  cart:
            total+=i.quantity*i.product.price
        ac=Account.objects.get(acctnumber=n)
        if(ac.amount>=total):
            ac.amount=ac.amount-total
            ac.save()
            for i in cart:
                o=Order.objects.create(user=user,product=i.product,address=a,phone=p,order_status='Paid',noofitems=i.quantity)
                o.save()
                i.product.stock=i.product.stock-i.quantity
                i.product.save()
            cart.delete()
            msg="Order has been placed successfully"
            return render(request,'orderview.html',{'msg':msg})


    return render(request,'orderform.html')

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Products
from django.db.models import Q

def searchresults(request):
    query=""
    product=None
    if(request.method=='POST'):
        query=request.POST['q']
        print(query)
        if(query):
            product=Products.objects.filter(Q(name__icontains=query)| Q(desc__icontains=query))

    return render(request,'search.html',{'product':product,'query':query})

ecommerce/shop/views.py
from django.shortcuts import render
from shop.models import Category,Products
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages

def allprodcat(request):
    f=Category.objects.all()
    return render(request,'category.html',{'f':f})

def allproducts(request,p):
    f=Category.objects.get(slug=p)
    p=Products.objects.filter(category__slug=p)
    return render(request,'products.html',{'p':p,'f':f})

def detail(request,p):
    p=Products.objects.get(slug=p)
    return render(request,'detail.html',{'p':p})

def register(request):
    if (request.method=="POST"):
        u=request.POST['u']
        f=request.POST['f']
        l=request.POST['l']
        e=request.POST['e']
        p=request.POST['p']
        z=User.objects.create_user(username=u,first_name=f,last_name=l,email=e,password=p)
        z.save()
        messages.success(request, "You have been registered")
    return render(request,'register.html')


def user_login(request):
    if (request.method == "POST"):
      u = request.POST['u']
      p = request.POST['p']
      user = authenticate(username=u, password=p)
      if user:
         login(request,user)
         return allprodcat(request)
      else:
          messages.error(request, "INVALID CREDENTIALS")
    return render(request,'login.html')

def user_logout(request):
    logout(request)
    return render(request,'category.html')

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&family=Roboto:wght@300&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
<div class="container-fluid">
    <center>
    <img src="{% static 'images/img.png' %}" height="120px" width="160px" >
        </center>
</div>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">SMILE SHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allprodcat' %}">Home</a>
        </li>
      </ul>
        <div class="collapse navbar-collapse" id="navbarSupportedContent1">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
         {% if user.is_authenticated %}
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            SHOP
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" >All Categories</a></li>
            <li><hr class="dropdown-divider"></li>
              {% for i in links %}
              <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.slug %}">{{i.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          <li class="nav-item">
          {% else %}
          <a class="nav-link active" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>
          {% endif %}
      <form method="POST" class="d-flex" action="{% url 'search:searchresults' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q"   placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
          <li class="nav-item">
          <a class="nav-link active text-primary" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i>{{count}}</a>
        </li>
      </ul>
     </div>
    </div>
  </div>
</nav>
<h1>WELCOME <i class="fa-solid fa-wand-magic-sparkles fa-sm"></i>
</h1>

{% block content %}
{% endblock %}

<footer>
    <div class="footer">
        <p><i class="fa-solid fa-copyright icon_size"></i>SmileShop pvt Ltd.All rights reserved</p>
    </div>
</footer>


</body>
</html>

ecommerce/templates/cartview.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}
{% if not cart %}
<div>
    <h1 class="text-center">Cart is empty</h1>
    <strong><a href="{% url 'shop:allprodcat' %}">Continue shopping</a></strong>
</div>

{% else %}
<div class="row">
    <h2 class="text-center">Shopping Cart</h2>
    <div class="col sm-6">
        <table class="table table-bordered border-primary">
            <tr>
                <th colspan="5">Cart Items</th>
            </tr>
            {% for i in cart %}
            <tr>
            <td>
                <td><img src="{{i.product.images.url}}" height="100px" width="100px"></td>
                <td><strong>{{i.product.name}}</strong></td>
                <td><strong>Price:{{i.product.price}}</strong>
                <p><strong> Quantity:{{i.quantity}}*{{i.product.price}}</strong></p>
                </td>
                <td><p>Subtotal:{{i.subtotal}}</p></td>
                <td>
                {% if i.quantity < i.product.stock %}
                    <a href="{% url 'cart:add_to_cart' i.product.id %}"><i class="fa-solid fa-plus"></i></a>
                    <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-minus"></i></a>
                    <a href="{% url 'cart:full_remove' i.product.id %}"><i class="fa-solid fa-trash"></i></a>
                {% else %}
                 <a href="{% url 'cart:cart_remove' i.product.id %}"></a><i class="fa-solid fa-minus"></i>
                <a href="{% url 'cart:full_remove' i.product.id %}"><i class="fa-solid fa-trash"></i></a>
                {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col sm-6">
       <table class="table table-bordered border-primary">
           <tr>
              <th colspan="5">CHECK OUT</th>
           </tr>
           <tr class="text-center">
               <td>TOTAL AMOUNT:{{total}}</td>
           </tr>
       </table>
        <a href="{% url 'cart:orderform' %}" class="btn btn-primary">Place Order</a>
        <a href="{% url 'shop:allprodcat' %}" style="position:absolute;right:0;" class="btn btn-primary">Continue Shopping</a>
    </div>
</div>


{% endif %}
  {% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div>
    <img src="{% static 'images/shop1.jpg' %}" height="200px" width="100%">
</div>
<div class="container-fluid" style="margin-bottom:100px;">
    <h2 class="text-center mb-2">Our Collections</h2>
    <p class=text-align:justify;">A typical online store enables the customer to
        browse the firm's range of products and services, view photos or images of the products,
        along with information about the product specifications, features and prices. Online stores
        usually enable shoppers to use "search" features to find specific models, brands or items.</p>
</div>

<div class="container-fluid mt-4" style="margin-bottom:100px">
    <div class="row">
        {% for i in f %}
        <div class="col-sm-4">
            <div class="card" style="width:24rem;height:100%;">
  <img src="{{i.images.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title text-center">{{i.name}}</h5>
    <p class="card-text" style="text-align:justify">{{i.desc}}</p>
    <a href="{% url 'shop:allproducts' i.slug %}" class="btn btn-primary" style="position:relative;left:38%">Products</a>
  </div>
</div>
        </div>
{% endfor %}


    </div>
</div>



{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<div class="container-fluid mt-4" style="margin-bottom:100px">
    <div class="row">
        <div class="col-sm-5">
  <img src="{{p.images.url}}" height="400px" width="400px">
        </div>

        <div class="col-sm-5">
    <h5 class="card-title text-center">{{p.name}}</h5>
    <h4>{{p.price}}</h4>
    <p>{{p.desc}}</p>
    {% if p.stock <= 0 %}
    <h4>Out of Stock</h4>
    {% else %}
     <h4 style="padding-top:10px;"><a href="{% url 'cart:add_to_cart' p.id %}" class="btn btn-primary">Add to Cart</a></h4>
            {% endif %}
  </div>
</div>
        </div>

    </div>
</div>

{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>LOGIN PAGE</h1>

<div class="container" style="margin-bottom:100px;">
    <form method="POST" class="border-primary">
        {% csrf_token %}
        <div class="mb-3">
          <label  class="form-label text-light">Username</label>
          <input type="text" class="form-control" name="u" placeholder="Enter your username">
        </div>
        <div class="mb-3">
          <label  class="form-label text-light">Password</label>
          <input type="password" class="form-control" name="p" placeholder="Enter the password to be given">
        </div>
        <div class="mb-3">

            <input type="submit" value="Register">
        </div>
    </form>
    {% if messages %}
    {% for i in messages %}
    <ul class="messages">
       <li>{{i}}</li>
    </ul>
    {% endfor %}
{% endif %}
</div>

{% endblock %}

ecommerce/templates/logout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>LOGOUT PAGE</h1>


{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form method="POST">
    {% csrf_token %}
<div class="container" style="margin-bottom:100px;">

    <div class="mb-3">
          <label  class="form-label ">Address</label>
          <input type="text" class="form-control"  name="a" placeholder="Enter the address">
    </div>
    <div class="mb-3">
          <label  class="form-label ">Phone</label>
          <input type="text" class="form-control"  name="p"  placeholder="Enter the phone number">
    </div>
    <div class="mb-3">
          <label  class="form-label ">Account Number</label>
          <input type="text" class="form-control"  name="n"  placeholder="Enter the account number">
    </div>
    <div class="mb-3">
        <input type="submit" class="btn btn-primary form-control">
    </div>
</div>
</form>
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>ORDER HAS BEEN PLACED SUCCESSFULLY</h1>


{% endblock %}

ecommerce/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div>
    <img src="{{f.images.url}}" height="400px" width="100%">
</div>
<div class="container-fluid" style="margin-bottom:100px;">
    <h2 class="text-center mb-2">{{f.name}}</h2>
    <p class=text-align:justify;">{{f.desc}}</p>
</div>

<div class="container-fluid mt-4" style="margin-bottom:100px">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card" style="width:24rem;height:100%;">
  <img src="{{i.images.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title text-center">{{i.name}}</h5>
    <h4 class="card-text" style="text-align:justify">{{i.price}}</h4>
    <a href="{% url 'shop:detail' i.slug %}" class="btn btn-primary" style="position:relative;left:38% text-align:center">DETAILS OF THE PRODUCT</a>
  </div>
</div>
        </div>
{% endfor %}


    </div>
</div>



{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>REGISTER PAGE</h1>

<form method="POST" class="border border-3 border-danger">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label text-light">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter your username">
</div>
  <div class="mb-3">
  <label class="form-label text-light">First name</label>
  <input type="text" class="form-control" name="f" placeholder="Enter your first name">
</div>
  <div class="mb-3">
    <label  class="form-label text-light">Last name</label>
  <input type="text" class="form-control" name="l" placeholder="Enter your last name">
</div>
  <div class="mb-3">
    <label  class="form-label text-light">E-mail</label>
  <input type="email" class="form-control" name="e" placeholder="Enter your email">
</div>
  <div class="mb-3">
    <label  class="form-label text-light">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the password to be given">
</div>
     <div class="mb-3">
    <input type="submit" value="Register">
    </div>
</form>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <div>
        <h4>You have searched for"{{query}}"</h4>
    </div>
</center>

<div class="container-fluid mt-4" style="margin-bottom:100px">
    <div class="row">
        {% for i in product %}
        <div class="col-sm-4">
            <div class="card" style="width:24rem;height:100%;">
  <img src="{{i.images.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title text-center">{{i.name}}</h5>
    <h4 class="card-text" style="text-align:justify">{{i.price}}</h4>
    <a href="{% url 'shop:detail' i.slug %}" class="btn btn-primary" style="position:relative;left:38% text-align:center">DETAILS OF THE PRODUCT</a>
  </div>
</div>
        </div>
        {% empty %}
        <h5 class="text-center text-danger">No Results Found</h5>

{% endfor %}

            </div>
</div>

{% endblock %}